export const CHANGE_PATH = 'CHANGE_PATH';

export const CHANGE_CURRENT_TIME = 'CHANGE_CURRENT_TIME';
export const CHANGE_PLAYING_SONG = 'CHANGE_PLAYING_SONG';
export const CHANGE_SELECTED_PLAYLISTS = 'CHANGE_SELECTED_PLAYLISTS';
export const RESET_AUTHED = 'RESET_AUTHED';
export const TOGGLE_IS_PLAYING = 'TOGGLE_IS_PLAYING';